### ISSUE TITLE
pypi package name

### ISSUE THREAD

**Issue by jayvdb** [Bernardo-MG/tox-test-command#7]
The readme says 'tox-test-command', but that is 404 https://pypi.org/project/tox-test-command/ , and it is actually under a different unnecessarily complicated name.

**Comment by Bernardo-MG** [comment]
The URL is https://pypi.org/project/bernardomg.tox-test-command/

I haven't had time to work on Python projects in a long time, and it seems that pypi has changed. I'll take a look as soon as possible.

**Comment by Bernardo-MG** [comment]
I've fixed the docs, now they tell the correct project name. That's as much as I can do about it.
